name: assigment_4
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0



dependencies:

  flutter:
    sdk: flutter
  iconly: ^1.0.1


  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  logger: ^2.5.0
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  get_it: ^8.0.3
  go_router: ^14.8.0
  hive_flutter: ^1.1.0
  get_storage_pro: ^0.1.5
  equatable: ^2.0.7
  flutter_spinkit: ^5.2.1


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.21.0


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/courses/
    - assets/images/


  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf